services:
  danilovl_select_autocompleter.form_type:
    class: Danilovl\SelectAutocompleterBundle\Form\Type\AutocompleterType
    arguments:
      - '@danilovl_select_autocompleter.container'
      - '@danilovl_select_autocompleter.resolver.form.autocompleter_type'
      - '@twig'
    tags:
      - { name: 'form.type', alias: 'autocompleter' }
