services:
  _defaults:
    autowire: true
    public: true

  Danilovl\SelectAutocompleterBundle\Form\Type\AutocompleterType:
    class: Danilovl\SelectAutocompleterBundle\Form\Type\AutocompleterType
    tags:
      - { name: 'form.type', alias: 'autocompleter' }

  Danilovl\SelectAutocompleterBundle\Form\Type\MultipleAutocompleterType:
    class: Danilovl\SelectAutocompleterBundle\Form\Type\MultipleAutocompleterType
    tags:
      - { name: 'form.type', alias: 'autocompleter' }
