services:
  danilovl.select_autocompleter.odm:
    class: Danilovl\SelectAutocompleterBundle\Services\OdmAutocompleter
    arguments:
      - '@doctrine_mongodb'
      - '@danilovl.select_autocompleter.resolver.config'
    abstract: true
