services:
  danilovl.select_autocompleter.orm:
    class: Danilovl\SelectAutocompleterBundle\Services\OrmAutocompleter
    arguments:
      - '@doctrine'
      - '@danilovl.select_autocompleter.resolver.config'
    abstract: true
