services:
  danilovl_select_autocompleter.orm:
    class: Danilovl\SelectAutocompleterBundle\Services\OrmAutocompleter
    arguments:
      - '@doctrine'
      - '@danilovl_select_autocompleter.resolver.config'
    abstract: true
