services:
  _defaults:
    autowire: true
    public: true

  Danilovl\SelectAutocompleterBundle\Service\AutocompleterContainer:
    arguments:
      - '@service_container'

  Danilovl\SelectAutocompleterBundle\Interfaces\AutocompleterContainerInterface: '@Danilovl\SelectAutocompleterBundle\Service\AutocompleterContainer'

  Danilovl\SelectAutocompleterBundle\Service\AutocompleterService:
    arguments:
      $container: '@service_container'

  Danilovl\SelectAutocompleterBundle\Controller\AutocompleterController: ~

  form.resolved_type_factory:
    class: Danilovl\SelectAutocompleterBundle\Proxy\AutocompleterResolvedFormTypeFactory
