services:
  danilovl.select_autocompleter.container:
    class: Danilovl\SelectAutocompleterBundle\Services\AutocompleterContainer
    arguments:
      - '@service_container'
    public: false

  danilovl.select_autocompleter.autocompleter:
    class: Danilovl\SelectAutocompleterBundle\Services\AutocompleterService
    arguments:
      - '@service_container'
      - '@danilovl.select_autocompleter.container'
      - '@security.token_storage'
    public: true