services:
  danilovl_select_autocompleter.voter.default:
    class: Danilovl\SelectAutocompleterBundle\Security\Voter\DefaultVoter
    public: true
    arguments:
      - '@security.helper'
    tags:
      - { name: security.voter }